name: Update Plot

on:
  schedule:
    # Run daily at midnight UTC (adjust cron time as needed)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  update-plot:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use your desired Python version

      # Install LaTeX dependencies
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended dvipng

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file in your repo

      # Run the script to generate the plot
      - name: Run script to generate plot
        run: |
          cd observations
          python Make_ObserveTable.py
          python Make_BarChart.py
          cd ..

      # Commit and push the updated plot
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/plot.png
          git commit -m 'Update plot [skip ci]' || echo "No changes to commit"
          git push
